<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Chrome launched]]>
    </line>
    <line>
      <![CDATA[navigating to url]]>
    </line>
  </reporter-output>
  <suite name="Suite1" duration-ms="12876" started-at="2019-08-27T10:12:33Z" finished-at="2019-08-27T10:12:46Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="12876" started-at="2019-08-27T10:12:33Z" finished-at="2019-08-27T10:12:46Z">
      <class name="com.actitime.scripts.TasksTest">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.actitime.scripts.TasksTest@724af044]" name="setUp" is-config="true" duration-ms="8959" started-at="2019-08-27T15:42:33Z" finished-at="2019-08-27T15:42:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Chrome launched]]>
            </line>
            <line>
              <![CDATA[navigating to url]]>
            </line>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="createCustomer()[pri:0, instance:com.actitime.scripts.TasksTest@724af044]" name="createCustomer" duration-ms="3886" started-at="2019-08-27T15:42:42Z" finished-at="2019-08-27T15:42:46Z">
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: nullat java.lang.Integer.parseInt(Unknown Source)at java.lang.Integer.parseInt(Unknown Source)at com.actitime.pageObjects.OpenTasksPage.clickOnProjNCustLink(OpenTasksPage.java:26)at com.actitime.scripts.TasksTest.createCustomer(TasksTest.java:23)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createCustomer -->
      </class> <!-- com.actitime.scripts.TasksTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite1 -->
</testng-results>
